### ISSUE TITLE
Is Transportation meant to be required?

### ISSUE THREAD

**Issue by mmcgrath** [AAVLD-USAHA-ITStandards/Permit#4]
On today's call it sounded like the intent was for `Transportation` to be optional but it is currently mandatory - see https://github.com/AAVLD-USAHA-ITStandards/Permit/blob/e0df3c08aa917c34f72bb2ea8e7cf80d86aab35b/Supplemental/schema_v1/src/movement_permit.xsd#L52

~~We will open a PR to address this as we feel it isn't practical to have this element as 'mandatory' for many classes of Permit.~~

We don't have permission to create a Pull Request.

**Comment by gustavo-etal** [comment]
Made it not mandatory
